# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor_1 = torch.rand(7, 7)
print(random_tensor_1)


tensor([[0.9146, 0.4857, 0.9897, 0.4013, 0.9432, 0.2919, 0.1010],
        [0.8209, 0.8486, 0.4972, 0.9105, 0.5339, 0.6335, 0.8699],
        [0.1084, 0.2271, 0.6317, 0.3220, 0.7060, 0.4931, 0.9421],
        [0.6548, 0.2367, 0.5953, 0.4383, 0.5729, 0.4775, 0.7881],
        [0.3520, 0.1960, 0.2563, 0.5441, 0.1483, 0.5906, 0.1394],
        [0.0883, 0.8874, 0.2236, 0.2731, 0.9039, 0.8073, 0.9863],
        [0.7356, 0.3149, 0.4954, 0.7789, 0.4509, 0.6892, 0.0244]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication 
result = torch.matmul(random_tensor_1, random_tensor_2.T)
print(result)


tensor([[1.8682],
        [2.5701],
        [1.6224],
        [1.8412],
        [1.0143],
        [2.3282],
        [1.5889]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
random_tensor_1 = torch.rand(7, 7)
random_tensor_2 = torch.rand(7, 1)

# Matrix multiply tensors
result = torch.matmul(random_tensor_1, random_tensor_2)
print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device)
tensor_B = torch.rand(2, 3).to(device)

print(tensor_A)
print(tensor_B)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_A, tensor_B.T)
print(result, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max_value = torch.max(result)
print(max_value)

# Find min
min_value = torch.min(result)
print(min_value)


tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
argmax_value = torch.argmax(result)
print(argmax_value)

# Find arg min
argmin_value = torch.argmin(result)
print(argmin_value)


tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
random_tensor_squeezed = torch.squeeze(random_tensor)

# Print out tensors and their shapes
print(f"Random tensor: {random_tensor}, shape: {random_tensor.shape}")
print(f"Squeezed tensor: {random_tensor_squeezed}, shap: {random_tensor_squeezed.shape}")


Random tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), shape: torch.Size([1, 1, 1, 10])
Squeezed tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), shap: torch.Size([10])
